// service-worker.js — gerado pelo Mini SK em 06/10/2026, 14:36:06
// Não precisa mexer: ele guarda sozinho o que o app usa.
const PREFIXO = 'sk-codelens-local-';
const CACHE = PREFIXO + 'muwymr5z';
// Lista feita automaticamente (para funcionar sem internet logo após instalar)
const GUARDAR = [
  "./",
  "./.npmrc",
  "./404.html",
  "./favicon.ico",
  "./hub.html",
  "./hub.webmanifest",
  "./icons/apple-touch-icon.png",
  "./icons/icon-16.png",
  "./icons/icon-32.png",
  "./icons/icon-48.png",
  "./icons/icon-72.png",
  "./icons/icon-96.png",
  "./icons/icon-128.png",
  "./icons/icon-144.png",
  "./icons/icon-152.png",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-384.png",
  "./icons/icon-512.png",
  "./icons/icon.svg",
  "./icons/maskable-192.png",
  "./icons/maskable-512.png",
  "./icons/maskable.svg",
  "./index.html",
  "./iniciar.bat",
  "./iniciar.sh",
  "./LEIA-ME.md",
  "./lib/api-client-react/index.ts",
  "./lib/api-zod/index.ts",
  "./lib/db/index.ts",
  "./manifest.json",
  "./package.json",
  "./public/favicon.svg",
  "./public/icons/icon-192.png",
  "./public/icons/icon-512.png",
  "./public/icons/icon.ico.png",
  "./public/icons/icon.png",
  "./public/manifest.json",
  "./public/opengraph.jpg",
  "./public/sw.js",
  "./scripts/abrir-pronto.mjs",
  "./scripts/iniciar.mjs",
  "./server/app.ts",
  "./server/index.ts",
  "./server/lib/devServerRegistry.ts",
  "./server/lib/logger.ts",
  "./server/lib/persistFiles.ts",
  "./server/lib/shell.ts",
  "./server/lib/storage.ts",
  "./server/routes/ai.ts",
  "./server/routes/code-assistant.ts",
  "./server/routes/code-run.ts",
  "./server/routes/dev-server.ts",
  "./server/routes/exec.ts",
  "./server/routes/files.ts",
  "./server/routes/github.ts",
  "./server/routes/health.ts",
  "./server/routes/import-github.ts",
  "./server/routes/index.ts",
  "./server/routes/preview.ts",
  "./server/routes/projects.ts",
  "./server/routes/settings.ts",
  "./server/routes/snippets.ts",
  "./src/App.tsx",
  "./src/components/ai-panel.tsx",
  "./src/components/code-editor.tsx",
  "./src/components/code-viewer.tsx",
  "./src/components/error-boundary.tsx",
  "./src/components/file-tree.tsx",
  "./src/components/github-deploy-modal.tsx",
  "./src/components/layout.tsx",
  "./src/components/packages-panel.tsx",
  "./src/components/preview-panel.tsx",
  "./src/components/terminal-panel.tsx",
  "./src/components/theme-provider.tsx",
  "./src/components/ui/accordion.tsx",
  "./src/components/ui/alert-dialog.tsx",
  "./src/components/ui/alert.tsx",
  "./src/components/ui/aspect-ratio.tsx",
  "./src/components/ui/avatar.tsx",
  "./src/components/ui/badge.tsx",
  "./src/components/ui/breadcrumb.tsx",
  "./src/components/ui/button-group.tsx",
  "./src/components/ui/button.tsx",
  "./src/components/ui/calendar.tsx",
  "./src/components/ui/card.tsx",
  "./src/components/ui/carousel.tsx",
  "./src/components/ui/chart.tsx",
  "./src/components/ui/checkbox.tsx",
  "./src/components/ui/collapsible.tsx",
  "./src/components/ui/command.tsx",
  "./src/components/ui/context-menu.tsx",
  "./src/components/ui/dialog.tsx",
  "./src/components/ui/drawer.tsx",
  "./src/components/ui/dropdown-menu.tsx",
  "./src/components/ui/empty.tsx",
  "./src/components/ui/field.tsx",
  "./src/components/ui/form.tsx",
  "./src/components/ui/hover-card.tsx",
  "./src/components/ui/input-group.tsx",
  "./src/components/ui/input-otp.tsx",
  "./src/components/ui/input.tsx",
  "./src/components/ui/item.tsx",
  "./src/components/ui/kbd.tsx",
  "./src/components/ui/label.tsx",
  "./src/components/ui/menubar.tsx",
  "./src/components/ui/navigation-menu.tsx",
  "./src/components/ui/pagination.tsx",
  "./src/components/ui/popover.tsx",
  "./src/components/ui/progress.tsx",
  "./src/components/ui/radio-group.tsx",
  "./src/components/ui/resizable.tsx",
  "./src/components/ui/scroll-area.tsx",
  "./src/components/ui/select.tsx",
  "./src/components/ui/separator.tsx",
  "./src/components/ui/sheet.tsx",
  "./src/components/ui/sidebar.tsx",
  "./src/components/ui/skeleton.tsx",
  "./src/components/ui/slider.tsx",
  "./src/components/ui/sonner.tsx",
  "./src/components/ui/spinner.tsx",
  "./src/components/ui/switch.tsx",
  "./src/components/ui/table.tsx",
  "./src/components/ui/tabs.tsx",
  "./src/components/ui/textarea.tsx",
  "./src/components/ui/toast.tsx",
  "./src/components/ui/toaster.tsx",
  "./src/components/ui/toggle-group.tsx",
  "./src/components/ui/toggle.tsx",
  "./src/components/ui/tooltip.tsx",
  "./src/hooks/use-file-ops.ts",
  "./src/hooks/use-mobile.tsx",
  "./src/hooks/use-toast.ts",
  "./src/index.css",
  "./src/lib/utils.ts",
  "./src/main.tsx",
  "./src/pages/assistant.tsx",
  "./src/pages/home.tsx",
  "./src/pages/not-found.tsx",
  "./src/pages/playground.tsx",
  "./src/pages/project-explorer.tsx",
  "./src/pages/settings.tsx",
  "./tsconfig.json",
  "./vite.config.ts",
  "./windows/Abrir-CodeLens.bat"
];

self.addEventListener('install', (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then((c) => Promise.all(GUARDAR.map((u) => c.add(u).catch(() => null)))));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((ks) => Promise.all(ks.filter((k) => k.startsWith(PREFIXO) && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Primeiro a internet (sempre a versão nova); sem internet, a cópia guardada.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    fetch(req).then((res) => {
      if (res.ok) { const copia = res.clone(); caches.open(CACHE).then((c) => c.put(req, copia)); }
      // Igual ao Workbox da Replit: página que não existe (rota do app) abre o index
      if (res.status === 404 && req.mode === 'navigate') return caches.match('./').then((r) => r || fetch('./'));
      return res;
    }).catch(() => caches.match(req, { ignoreSearch: true }).then((r) => r || (req.mode === 'navigate' ? caches.match('./') : undefined)))
  );
});
